# Generated by Django 5.0.1 on 2024-03-12 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('area_of_interest', models.CharField(choices=[('Select Here', 'Select Here'), ('Tech', 'Tech'), ('Business', 'Business'), ('Company', 'Company'), ('Education', 'Education'), ('Bank', 'Bank'), ('Remote', 'remote')], max_length=255)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('New_Application_Submitted', 'New_Application_Submitted'), ('Application_Approved', 'Application_Approved'), ('Application_Declined', 'Application_Declined')], default='Application_Approved', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('dob', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(upload_to='cover_letter/')),
                ('apply_now', models.BooleanField(choices=[('apply_now', 'apply_now'), ('apply_later', 'apply_later')], default=False)),
                ('apply_later', models.BooleanField(choices=[('apply_now', 'apply_now'), ('apply_later', 'apply_later')], default=False)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Delete', 'Delete'), ('Aproved', 'Aproved')], default='Pending', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('New_Application_Submitted', 'New_Application_Submitted'), ('Application_Approved', 'Application_Approved'), ('Application_Declined', 'Application_Declined')], default='New_Application_Submitted', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='AdminDashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('New_Application_Submitted', 'New_Application_Submitted'), ('Application_Approved', 'Application_Approved'), ('Application_Declined', 'Application_Declined')], max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=500)),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('area_of_interest', models.CharField(choices=[('Select Here', 'Select Here'), ('Tech', 'Tech'), ('Business', 'Business'), ('Company', 'Company'), ('Education', 'Education'), ('Bank', 'Bank'), ('Remote', 'remote')], max_length=255)),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('New_Application_Submitted', 'New_Application_Submitted'), ('Application_Approved', 'Application_Approved'), ('Application_Declined', 'Application_Declined')], default='Application_Approved', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(default=1, max_length=50, null=True)),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('activation_key', models.CharField(blank=True, max_length=300, null=True)),
                ('is_profile_updated', models.BooleanField(default=False)),
                ('job_area_of_interest', models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Business', 'Business'), ('Company', 'Company'), ('Education', 'Education'), ('Bank', 'Bank'), ('Remote', 'remote')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
